### ISSUE TITLE
GaloisField contructor with non prime p^n-1 

### ISSUE THREAD

**Issue by RedCuckoo** [WAG13/Algebra-polynom#51] opened 2020-06-03 13:57 UTC
Ways to reproduce: enter p=2 and n=9. It works perfectly with p=2 and n=10 but crashes on other values.

**Comment by gardenappl** [comment] 2020-06-05 14:34
Our program is perfect, this is intended behavior. Closing issue.

**Closed by gardenappl** 2020-06-05 14:34 UTC
